- name: Ensure port on AG 1-5 is RUNNING
  hosts: group-nbp-inventory-prd-ag15
  gather_facts: False
  tasks: 
  - name: Checking...
    wait_for:
     host: 0.0.0.0
     port: "{{ item }}"
     delay: 10
     state: started
    with_items:
      - 8002
      - 9020
      - 54002
      - 55000
      - 55001
      - 55003
      - 55004
      - 54000
      - 54001
      - 54003
    when: your_choice == "1"
    
- name: Ensure port on AMR is RUNNING
  hosts: 10.251.25.200
  gather_facts: False
  tasks: 
  - name: Checking...
    wait_for:
     host: 0.0.0.0
     port: "{{ item }}"
     delay: 10
     state: started
    with_items:
      - 9014
      - 9015
      - 9017
      - 8444
      - 9101
      - 9102
      - 9103
    when: your_choice == "2"
    
- name: Ensure port on AG 6 is RUNNING
  hosts: 10.251.25.199
  gather_facts: False
  tasks: 
  - name: Checking...
    wait_for:
     host: 0.0.0.0
     port: "{{ item }}"
     delay: 10
     state: started
    with_items:
      - 8002
      - 9020
    when: your_choice == "3"
