- hosts: 10.0.50.62

  tasks:

  - name: get the corresponding playbook
    include_tasks: one.yml
    when: make_your_choice == "1"

  - name: get the corresponding playbook
    include_tasks: two.yml
    when: make_your_choice == "2"
